/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gabrielalvarado_lab5;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Gabriel Alvarado
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
        DefaultListModel model = (DefaultListModel) jl_equipos2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_presupuesto = new javax.swing.JTextField();
        tf_numero = new javax.swing.JTextField();
        tf_estadio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        cb_posicion = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_habilidad = new javax.swing.JTextField();
        tf_tecnica = new javax.swing.JTextField();
        tf_resistencia = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        rb_d = new javax.swing.JRadioButton();
        rd_c = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_equipos = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        tf_total = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombre2 = new javax.swing.JTextField();
        tf_presupuesto1 = new javax.swing.JTextField();
        tf_numero1 = new javax.swing.JTextField();
        tf_estadio1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        rd_c1 = new javax.swing.JRadioButton();
        rb_d1 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cb_posicion1 = new javax.swing.JComboBox();
        tf_precio1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombre3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_habilidad1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_tecnica1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_resistencia1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_equipos = new javax.swing.JTree();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_equipos2 = new javax.swing.JList();
        jButton11 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Equipos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 25, 95, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Presupuesto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Numero de copas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 287, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Estadio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        jPanel1.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 250, -1));
        jPanel1.add(tf_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 250, -1));
        jPanel1.add(tf_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 250, -1));
        jPanel1.add(tf_estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 260, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, 20));

        jTabbedPane1.addTab("Agregar Equipos", jPanel1);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Jugadores");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 25, 130, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Precio");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Posicion");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Disponibilidad");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel6.add(tf_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, -1));
        jPanel6.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, -1));

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atacante", "medio", "Campista", "Defensa", "Portero", " " }));
        jPanel6.add(cb_posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Hablidad");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Tecnica");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Resistencia");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));
        jPanel6.add(tf_habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 170, -1));

        tf_tecnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tecnicaActionPerformed(evt);
            }
        });
        jPanel6.add(tf_tecnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 170, -1));
        jPanel6.add(tf_resistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 170, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        rb_d.setText("Disponible");
        jPanel6.add(rb_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        rd_c.setText("Comprado");
        jPanel6.add(rd_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jTabbedPane1.addTab("Agregar jugadores", jPanel6);

        jl_equipos.setModel(new DefaultListModel()
        );
        jl_equipos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jl_equiposValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jl_equipos);

        jButton5.setText("Cargar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel27.setText("Listar Equipos");

        jButton6.setText("Comprar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel28.setText("Presupuesto");

        jButton9.setText("Eliminar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel28))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButton6))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel27))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton5)
                        .addGap(104, 104, 104)
                        .addComponent(jButton9)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel27)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton9))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Equipos", jPanel13);

        jl_jugadores.setModel(new DefaultListModel()
        );
        jl_jugadores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jl_jugadoresValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jl_jugadores);

        jButton8.setText("Cargar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Eliminar");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jButton8)
                        .addGap(115, 115, 115)
                        .addComponent(jButton10)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton10))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Jugador", jPanel14);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jTabbedPane4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane4StateChanged(evt);
            }
        });

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Equipos");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 95, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Nombre");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Presupuesto");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Numero de copas");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 287, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Estadio");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        jPanel12.add(tf_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 250, -1));
        jPanel12.add(tf_presupuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 250, -1));
        jPanel12.add(tf_numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 250, -1));
        jPanel12.add(tf_estadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 260, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, 30));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 490));

        jTabbedPane4.addTab("Equipos", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rd_c1.setText("Comprado");
        jPanel10.add(rd_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        rb_d1.setText("Disponible");
        jPanel10.add(rb_d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Disponibilidad");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Posicion");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        cb_posicion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atacante", "medio", "Campista", "Defensa", "Portero", " " }));
        jPanel10.add(cb_posicion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, -1));
        jPanel10.add(tf_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Precio");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Nombre");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        tf_nombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombre3ActionPerformed(evt);
            }
        });
        jPanel10.add(tf_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Jugadores");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 130, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("Hablidad");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));
        jPanel10.add(tf_habilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 170, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("Tecnica");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        tf_tecnica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tecnica1ActionPerformed(evt);
            }
        });
        jPanel10.add(tf_tecnica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 170, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Resistencia");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));
        jPanel10.add(tf_resistencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 170, -1));

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jTabbedPane4.addTab("Jugadores", jPanel10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 513, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar y eliminar", jPanel3);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_equipos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_equipos);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 250, 320));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setText("---->");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 170, 100));

        jl_equipos2.setModel(new DefaultListModel()
        );
        jScrollPane4.setViewportView(jl_equipos2);

        jPanel11.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 310));

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 150, 80));

        jTabbedPane1.addTab("Arbol", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_tecnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tecnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tecnicaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = tf_nombre.getText();
        int presupuesto = Integer.parseInt(tf_presupuesto.getText());
        int copas = Integer.parseInt(tf_numero.getText());
        String estadio = tf_estadio.getText();
        Equipo e = new Equipo(nombre, copas, estadio, presupuesto);
        ListEquipo.add(e);
        DefaultListModel model = (DefaultListModel) jl_equipos.getModel();
        model.addElement(e);
        jl_equipos.setModel(model);
        jl_equipos2.setModel(model);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = tf_nombre1.getText();
        int precio = Integer.parseInt(tf_precio.getText());
        String posicion = cb_posicion.getSelectedItem().toString();
        String habilidad = tf_habilidad.getText();
        String tecnica = tf_tecnica.getText();
        int resistencia = Integer.parseInt(tf_resistencia.getText());
        boolean disponible = false;
        boolean comprado;
        if (rb_d.isSelected()) {
            disponible = true;
        }
        if (rd_c.isSelected()) {
            disponible = false;
        }
        Jugador j = new Jugador(nombre, precio, posicion, disponible, habilidad, tecnica, resistencia);
        ListJugador.add(j);
        DefaultListModel model = (DefaultListModel) jl_jugadores.getModel();
        model.addElement(j);
        jl_jugadores.setModel(model);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jl_equiposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jl_equiposValueChanged

    }//GEN-LAST:event_jl_equiposValueChanged

    private void jl_jugadoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jl_jugadoresValueChanged

    }//GEN-LAST:event_jl_jugadoresValueChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        pos = jl_jugadores.getSelectedIndex();
        jl_jugadores.remove(pos2);
        DefaultListModel model = (DefaultListModel) jl_jugadores.getModel();
        for (Jugador t : ListJugador) {
            model.addElement(t);
        }
        jl_jugadores.setModel(model);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTabbedPane4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane4StateChanged

    }//GEN-LAST:event_jTabbedPane4StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pos2 = jl_jugadores.getSelectedIndex();

        String nombre = tf_nombre3.getText();
        int precio = Integer.parseInt(tf_precio1.getText());
        String posicion = cb_posicion1.getSelectedItem().toString();
        String habilidad = tf_habilidad1.getText();
        String tecnica = tf_tecnica1.getText();
        int resistencia = Integer.parseInt(tf_resistencia.getText());
        boolean disponible = false;
        boolean comprado;
        if (rb_d.isSelected()) {
            disponible = true;
        }
        if (rd_c.isSelected()) {
            disponible = false;
        }
        ListJugador.get(pos2).setDisponibilidad(disponible);
        ListJugador.get(pos2).setHabilidad(habilidad);
        ListJugador.get(pos2).setNombre(nombre);
        ListJugador.get(pos2).setPrecio(precio);
        ListJugador.get(pos2).setResistencia(resistencia);
        ListJugador.get(pos2).setTecnica(tecnica);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tf_tecnica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tecnica1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tecnica1ActionPerformed

    private void tf_nombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombre3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pos = jl_equipos.getSelectedIndex();
        String nombre = tf_nombre2.getText();
        int presupuesto = Integer.parseInt(tf_presupuesto1.getText());
        int copas = Integer.parseInt(tf_numero1.getText());
        String estadio = tf_estadio1.getText();
        ListEquipo.get(pos).setNombre(nombre);
        ListEquipo.get(pos).setEstadio(estadio);
        ListEquipo.get(pos).setCopas(copas);
        ListEquipo.get(pos).setPresupuesto(presupuesto);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int dinero = ListEquipo.get(pos).getPresupuesto();
        int precioJ = ListJugador.get(pos2).getPrecio();
        int total = dinero - precioJ;
        if (total < 0) {
            tf_total.setText(Integer.toString(total));
        } else {
            JOptionPane.showMessageDialog(this, "No hay money");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jl_equipos2.getSelectedIndex() >= 0) {
            Equipo e = new Equipo();
            DefaultTreeModel m = (DefaultTreeModel) jt_equipos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            String nombre = tf_nombre1.getText();
            int precio = Integer.parseInt(tf_precio.getText());
            String posicion = cb_posicion.getSelectedItem().toString();
            String habilidad = tf_habilidad.getText();
            String tecnica = tf_tecnica.getText();
            int resistencia = Integer.parseInt(tf_resistencia.getText());
            boolean disponible = false;
            boolean comprado;
            if (rb_d.isSelected()) {
                disponible = true;
            }
            if (rd_c.isSelected()) {
                disponible = false;
            }
            //obtener la persona a guardar
            DefaultListModel lista = (DefaultListModel) jl_equipos2.getModel();
            Jugador t = (Jugador) lista.get(jl_equipos2.getSelectedIndex());

            //ver si ya existe la nacionalidad
            int centinela = -1;

            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(e.getNombre())) {

                    //si ya existe la agrega la persona
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Jugador(nombre, precio, posicion, disponible, habilidad, tecnica, resistencia));
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;

                }

            }
            if (centinela == 1) {
                DefaultMutableTreeNode n
                        = (new DefaultMutableTreeNode(e.getNombre()));
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(new Jugador(nombre, precio, posicion, disponible, habilidad, tecnica, resistencia));
                n.add(p);
                raiz.add(n);
            }
            m.reload();
        } else {
            JOptionPane.showMessageDialog(this, "no hay persona seleccionada");

        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged


    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     DefaultTreeModel m = (DefaultTreeModel) jt_equipos.getModel();
     String nombre = tf_nombre.getText();
        int presupuesto = Integer.parseInt(tf_presupuesto.getText());
        int copas = Integer.parseInt(tf_numero.getText());
        String estadio = tf_estadio.getText();
        Equipo e = new Equipo(nombre, copas, estadio, presupuesto);
        ListEquipo.add(e);
        DefaultListModel model = (DefaultListModel) jl_equipos.getModel();
        model.addElement(e);
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo;
        nodo = new DefaultMutableTreeNode(new Equipo(nombre, copas, estadio, presupuesto));

        DefaultMutableTreeNode jugador;
        jugador= new DefaultMutableTreeNode(new Jugador());
       
        raiz.add(nodo);
        jugador.add(raiz);
        

        m.reload();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_posicion;
    private javax.swing.JComboBox cb_posicion1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JList jl_equipos;
    private javax.swing.JList jl_equipos2;
    private javax.swing.JList jl_jugadores;
    private javax.swing.JTree jt_equipos;
    private javax.swing.JRadioButton rb_d;
    private javax.swing.JRadioButton rb_d1;
    private javax.swing.JRadioButton rd_c;
    private javax.swing.JRadioButton rd_c1;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_estadio1;
    private javax.swing.JTextField tf_habilidad;
    private javax.swing.JTextField tf_habilidad1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_nombre3;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_numero1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_presupuesto;
    private javax.swing.JTextField tf_presupuesto1;
    private javax.swing.JTextField tf_resistencia;
    private javax.swing.JTextField tf_resistencia1;
    private javax.swing.JTextField tf_tecnica;
    private javax.swing.JTextField tf_tecnica1;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
ArrayList<Jugador> ListJugador = new ArrayList();
    ArrayList<Equipo> ListEquipo = new ArrayList();
    int pos;
    int pos2;

}
